a_cool_guy: "Falco Lombardi"
camera:
    John:
      resolution: 2x2
      name: John
    Fitz:
      resolution: 4x4
      name: Fitz
    Herald:
      resolution: 16x16
      name: Herald
    Ken:
      resolution: 32x32
      name: Ken
    Eddy:
      resolution: 64x64
      name: Eddy
